version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.deploy
    image: assistant-python
    container_name: assistant-python
    ports:
      - "9898:9000"
    env_file:
      - ./envs/.env.local
    environment:
      - ENVIRONMENT=local
    volumes:
      - .:/application
